# Generated by Django 4.1 on 2022-08-29 10:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentsInitiators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, help_text='UUID сотрудника, поручения от которого будут учитываться в КИД.', max_length=50, null=True, unique=True, verbose_name='UUID сотрудника')),
                ('name', models.CharField(help_text='Имя сотрудника (используется только для отображения в таблице администратора).', max_length=500, verbose_name='Имя сотрудника')),
            ],
            options={
                'verbose_name': 'инициатор поручений',
                'verbose_name_plural': 'инициаторы поручений',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentsSources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_source', models.CharField(help_text='Источник поручения, учитываемый в расчете КИД.', max_length=500, unique=True, verbose_name='Источник поручения')),
                ('coefficient', models.PositiveIntegerField(default=1, help_text='Важность поручения от 1 до 3.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Важность поручения')),
            ],
            options={
                'verbose_name': 'источник поручений',
                'verbose_name_plural': 'источники поручений',
                'ordering': ['-coefficient', 'assignment_source'],
            },
        ),
        migrations.CreateModel(
            name='ExcludedOrganizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название организации, которая будет исключена из отчетов.', max_length=500, unique=True, verbose_name='Название организации')),
            ],
            options={
                'verbose_name': 'исключенная организация',
                'verbose_name_plural': 'исключенные организации',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name'], 'verbose_name': 'сотрудник', 'verbose_name_plural': 'сотрудники'},
        ),
        migrations.AddField(
            model_name='person',
            name='uuid',
            field=models.UUIDField(default=None, help_text='Можно узнать в системе ТЕЗИС, либо в отладке отчетов приложения.', unique=True, verbose_name='UUID сотрудника'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(help_text='Имя сотрудника, как оно записано в системе ТЕЗИС.', max_length=100, verbose_name='Имя сотрудника'),
        ),
        migrations.CreateModel(
            name='ReportKid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reports_count', models.BigIntegerField(verbose_name='Количество поручений')),
                ('reports_completed_on_time_count', models.BigIntegerField(verbose_name='Количество поручений, выполненных в срок')),
                ('reports_completed_out_time_count', models.BigIntegerField(verbose_name='Количество поручений, выполненых с нарушением срока')),
                ('reports_incompleted_count', models.BigIntegerField(verbose_name='Количество поручений, выполненых с нарушением срока')),
                ('name', models.OneToOneField(help_text='Сотрудник, который будет будет отображаться в отчете КИД.', on_delete=django.db.models.deletion.CASCADE, to='server.person', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'сотрудники',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExecutorsDependencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curator', to='server.reportkid', verbose_name='Руководитель')),
                ('dependants', models.ManyToManyField(related_name='dependants', to='server.reportkid', verbose_name='Подчиненные')),
            ],
            options={
                'verbose_name': 'список подчиненных',
                'verbose_name_plural': 'списки подчиненных',
                'ordering': ['curator'],
            },
        ),
    ]
