# Generated by Django 4.1 on 2022-08-29 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_assignmentsinitiators_assignmentssources_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmentsinitiators',
            options={'ordering': ['person'], 'verbose_name': 'инициатор поручений', 'verbose_name_plural': 'инициаторы поручений'},
        ),
        migrations.AlterModelOptions(
            name='reportkid',
            options={'ordering': ['person'], 'verbose_name': 'исполнитель КИД', 'verbose_name_plural': 'исполнители КИД'},
        ),
        migrations.RemoveField(
            model_name='assignmentsinitiators',
            name='name',
        ),
        migrations.RemoveField(
            model_name='assignmentsinitiators',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='reportkid',
            name='name',
        ),
        migrations.AddField(
            model_name='assignmentsinitiators',
            name='person',
            field=models.OneToOneField(default=None, error_messages={'unique': 'Этот сотрудник уже есть в таблице инициаторов КИД.'}, help_text='Сотрудник, поручения которого будут учитываться в КИД.', on_delete=django.db.models.deletion.CASCADE, to='server.person', verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='reportkid',
            name='person',
            field=models.OneToOneField(default=None, error_messages={'unique': 'Этот сотрудник уже есть в таблице исполнителей КИД.'}, help_text='Сотрудник, который будет будет отображаться в отчете КИД.', on_delete=django.db.models.deletion.CASCADE, to='server.person', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='reportkid',
            name='reports_completed_on_time_count',
            field=models.BigIntegerField(default=0, verbose_name='Количество поручений, выполненных в срок'),
        ),
        migrations.AlterField(
            model_name='reportkid',
            name='reports_completed_out_time_count',
            field=models.BigIntegerField(default=0, verbose_name='Количество поручений, выполненых с нарушением срока'),
        ),
        migrations.AlterField(
            model_name='reportkid',
            name='reports_count',
            field=models.BigIntegerField(default=0, verbose_name='Количество поручений'),
        ),
        migrations.AlterField(
            model_name='reportkid',
            name='reports_incompleted_count',
            field=models.BigIntegerField(default=0, verbose_name='Количество поручений, выполненых с нарушением срока'),
        ),
    ]
