# Generated by Django 4.1 on 2022-08-29 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_assignmentsinitiators_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executorsdependencies',
            name='curator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='server.person', verbose_name='Руководитель'),
        ),
        migrations.AlterField(
            model_name='executorsdependencies',
            name='dependants',
            field=models.ManyToManyField(to='server.reportkid', verbose_name='Подчиненные'),
        ),
    ]
