# Generated by Django 4.1 on 2022-08-30 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_alter_executorsdependencies_curator_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmentsinitiators',
            options={'ordering': ['person'], 'verbose_name': 'инициатор КИД', 'verbose_name_plural': 'инициаторы КИД'},
        ),
    ]
