# Generated by Django 4.1 on 2022-08-30 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_alter_assignmentsinitiators_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuratorsKid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='server.person', verbose_name='Куратор')),
                ('dependants', models.ManyToManyField(to='server.reportkid', verbose_name='Подчиненные')),
            ],
            options={
                'verbose_name': 'куратор КИД',
                'verbose_name_plural': 'кураторы КИД',
                'ordering': ['curator'],
            },
        ),
        migrations.DeleteModel(
            name='ExecutorsDependencies',
        ),
    ]
