# Generated by Django 4.1 on 2022-08-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_curatorskid_delete_executorsdependencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='curatorskid',
            name='date_end',
            field=models.DateField(auto_now=True, verbose_name='До'),
        ),
        migrations.AddField(
            model_name='curatorskid',
            name='date_start',
            field=models.DateField(auto_now=True, verbose_name='От'),
        ),
    ]
