# Generated by Django 4.1 on 2022-08-30 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_curatorskid_date_end_curatorskid_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curatorskid',
            name='date_end',
            field=models.DateField(default=datetime.date(2022, 8, 30), verbose_name='До'),
        ),
        migrations.AlterField(
            model_name='curatorskid',
            name='date_start',
            field=models.DateField(default=datetime.date(2022, 8, 30), verbose_name='От'),
        ),
    ]
