# Generated by Django 4.1 on 2022-08-30 06:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_alter_curatorskid_date_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curatorskid',
            name='date_end',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='До'),
        ),
        migrations.AlterField(
            model_name='curatorskid',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='От'),
        ),
    ]
