# Generated by Django 4.1 on 2022-08-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_alter_curatorskid_options_alter_curatorskid_curator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportkid',
            name='pnc_coefficient',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=11, verbose_name='Пнс'),
        ),
    ]
