# Generated by Django 4.1 on 2022-09-05 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_remove_reportkid_pnc_coefficient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='deputy_governor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.OneToOneField(default=None, error_messages={'unique': 'Этот сотрудник уже есть в таблице исполнителей КИД.'}, help_text='Заместитель губернатора, который будет будет отображаться в отчете КИД.', on_delete=django.db.models.deletion.CASCADE, to='server.person', verbose_name='Заместитель губернатора')),
            ],
            options={
                'verbose_name': 'заместитель губернатора',
                'verbose_name_plural': 'заместители губернатора',
                'ordering': ['person'],
            },
        ),
    ]
