# Generated by Django 4.1 on 2022-09-05 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_deputy_governor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='deputy_governor',
            new_name='DeputyGovernor',
        ),
    ]
