# Generated by Django 4.1 on 2022-09-05 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_minister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deputygovernor',
            name='person',
            field=models.OneToOneField(default=None, error_messages={'unique': 'Этот сотрудник уже есть в таблице исполнителей КИД.'}, help_text='Заместитель губернатора, который будет отображаться в отчете КИД.', on_delete=django.db.models.deletion.CASCADE, to='server.person', verbose_name='Заместитель губернатора'),
        ),
        migrations.AlterField(
            model_name='minister',
            name='person',
            field=models.OneToOneField(default=None, error_messages={'unique': 'Этот сотрудник уже есть в таблице исполнителей КИД.'}, help_text='Министр, который будет отображаться в отчете КИД.', on_delete=django.db.models.deletion.CASCADE, to='server.person', verbose_name='Министр'),
        ),
    ]
