# Generated by Django 4.1 on 2022-09-06 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0017_alter_deputygovernor_person_alter_minister_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curatorskid',
            options={'ordering': ['curator'], 'verbose_name': 'куратор КИД', 'verbose_name_plural': 'кураторы КИД'},
        ),
        migrations.AlterUniqueTogether(
            name='curatorskid',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='curatorskid',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='curatorskid',
            name='date_start',
        ),
    ]
