# Generated by Django 4.1 on 2022-09-06 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0018_alter_curatorskid_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curatorskid',
            name='curator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='curator', to='server.person', verbose_name='Куратор'),
        ),
    ]
