# Generated by Django 4.1.3 on 2022-11-02 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0019_alter_curatorskid_curator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curatorskid',
            name='curator',
            field=models.OneToOneField(error_messages={'unique': 'Этот сотрудник уже есть в таблице кураторов КИД.'}, help_text='Сотрудник, которому будут прибавляться поручения его подчиненных.', on_delete=django.db.models.deletion.CASCADE, related_name='curator', to='server.person', verbose_name='Куратор'),
        ),
    ]
